### ISSUE TITLE
lyrics addon docker: "processing: process addon: write new lyrics: can't save file"

### ISSUE THREAD

**Issue by gabeklavans** [sentriz/wrtag#81]
I've tried using default root permissions in the container as well as matching the permissions on my music files to 1000:100 (I'm in Unraid) both inside and outside the container. I go into the container and run `wrtag move /path/to/release`. It can move the music files just fine, but when it tries to save the lyrics, I get:
```
time=2025-03-16T05:36:55.789Z level=DEBUG msg=response status=200 url="https://musicbrainz.org/ws/2/release/8161f3af-1d51-4dc8-b3b4-3a74c3f8cf4a?fmt=json&inc=recordings%2Bartist-credits%2Blabels%2Brelease-groups%2Bgenres" took=364.894451ms
time=2025-03-16T05:36:56.161Z level=DEBUG msg=response status=404 url=https://www.musixmatch.com/lyrics/Anamanaguchi/-U-S-A- took=120.993912ms
time=2025-03-16T05:36:56.543Z level=DEBUG msg=response status=200 url=https://www.musixmatch.com/lyrics/Anamanaguchi/Overwriting-Incorporate took=2.463181ms
time=2025-03-16T05:36:57.046Z level=DEBUG msg=response status=200 url=https://www.musixmatch.com/lyrics/Anamanaguchi/The-C-R-T-Woods took=5.111569ms
time=2025-03-16T05:36:57.547Z level=DEBUG msg=response status=200 url=https://www.musixmatch.com/lyrics/Anamanaguchi/Up-to-You took=6.540854ms
time=2025-03-16T05:36:58.050Z level=DEBUG msg=response status=200 url=https://www.musixmatch.com/lyrics/Anamanaguchi/Tear took=8.323315ms
time=2025-03-16T05:36:58.551Z level=DEBUG msg=response status=200 url=https://www.musixmatch.com/lyrics/Anamanaguchi/Sunset-by-Plane took=10.194909ms
time=2025-03-16T05:36:59.044Z level=DEBUG msg=response status=200 url=https://www.musixmatch.com/lyrics/Anamanaguchi/We-Die took=3.60465ms
time=2025-03-16T05:36:59.546Z level=DEBUG msg=response status=200 url=https://www.musixmatch.com/lyrics/Anamanaguchi/Lorem-Ipsum-Arctic-Anthem took=5.683668ms
time=2025-03-16T05:37:00.048Z level=DEBUG msg=response status=200 url=https://www.musixmatch.com/lyrics/Anamanaguchi/Air-on-Line took=7.660865ms
time=2025-03-16T05:37:00.550Z level=DEBUG msg=response status=200 url=https://www.musixmatch.com/lyrics/Anamanaguchi/On-My-Own took=9.505886ms
time=2025-03-16T05:37:01.067Z level=DEBUG msg=response status=404 url=https://www.musixmatch.com/lyrics/Anamanaguchi/-L-O-M- took=26.633782ms
time=2025-03-16T05:37:01.545Z level=DEBUG msg=response status=200 url=https://www.musixmatch.com/lyrics/Anamanaguchi/Apophenia-Light-Name-Eaters took=4.742649ms
time=2025-03-16T05:37:02.047Z level=DEBUG msg=response status=200 url=https://www.musixmatch.com/lyrics/Anamanaguchi/Speak-to-You-Memory-Messengers took=5.51061ms
time=2025-03-16T05:37:02.550Z level=DEBUG msg=response status=200 url=https://www.musixmatch.com/lyrics/Anamanaguchi/B-S-X took=9.076677ms
time=2025-03-16T05:37:02.556Z level=ERROR msg=running command=move err="processing: process addon: write new lyrics: can't save file\nwrite new lyrics: can't save file\nwrite new lyrics: can't save file\nwrite new lyrics: can't save file\nwrite new lyrics: can't save file\nwrite new lyrics: can't save file\nwrite new lyrics: can't save file\nwrite new lyrics: can't save file\nwrite new lyrics: can't save file\nwrite new lyrics: can't save file\nwrite new lyrics: can't save file\nwrite new lyrics: can't save file\nwrite new lyrics: can't save file\nwrite new lyrics: can't save file"
```
I also get this when I try to run from wrtagweb exposed by the container.

Here's my compose file:
```yml
services:
  wrtag:
    image: ghcr.io/sentriz/wrtag
    user: 1000:100
    container_name: wrtag
    environment:
      - WRTAG_WEB_API_KEY=<key>
      - WRTAG_WEB_LISTEN_ADDR=:80
      - WRTAG_WEB_PUBLIC_URL=https://wrtag.vpn.dabe.tech
      - WRTAG_WEB_DB_PATH=/data/wrtag.db
      - WRTAG_LOG_LEVEL=debug
      - WRTAG_PATH_FORMAT=/music/{{ artists .Release.Artists | sort | join "; " | safepath }}/({{ .Release.ReleaseGroup.FirstReleaseDate.Year }}) {{ .Release.Title | safepath }}{{ if not (eq .ReleaseDisambiguation "") }} ({{ .ReleaseDisambiguation | safepath }}){{ end }}/{{ .TrackNum }}. {{ if .IsCompilation }}{{ artistsString .Track.Artists | safepath }} - {{ end }}{{ .Track.Title | safepath }}{{ .Ext }}
      - WRTAG_ADDON=lyrics musixmatch,replaygain
      - "WRTAG_NOTIFICATION_URI=needs-input telegram://<mytoken>@telegram/?channels=<mychannel>"
    expose:
      - 80
    volumes:
      - /mnt/user/elysium/wrtag/data:/data # for the wrtagweb job queue DB
      - /mnt/user/tartarus/audio/music:/music
      - /mnt/user/tartarus/audio/music.old:/mnt/music
    networks:
      - internal
    labels:
      - internal=true
      - subdomain=wrtag
      - "traefik.http.services.wrtag-wrtag.loadbalancer.server.port=80"

networks:
  internal:
    external: true
```

Edit: Yes, I did leak my TG bot token. I have regenerated it lol
